### ISSUE TITLE
fail compile electron_rom-emulator

### ISSUE THREAD

**Issue by retrocant** [kernelcrash/electron-rom-emulator#1]

**Comment by retrocant** [comment]
Greetings, I'm having problems in the compilation, I'm generating it with mac os and I get enough errors please can you indicate what files I need and versions?
stm32f4xx.h and system_stm32f4xx.h
attached capture
![Captura de pantalla 2019-03-28 a las 21 45 44](https://user-images.githubusercontent.com/23484201/55191591-de70d880-51a2-11e9-969f-2ff8156dde00.png)

**Comment by kernelcrash** [comment]
I'm just using the st.com 'Standard Peripheral Library'. I used the one for the STM32F4Discovery ; http://www.st.com/web/en/catalog/tools/PF257904# . I end up with a en.stsw-stm32068.zip .I haven't tried compilation on OSX. Only on Linux.

**Comment by retrocant** [comment]
I am currently doing the compilation in ubuntu 18.04 I have the libraries that are necessary but I ask for the library stm32f4xx.h that I do not have, I would like to know which version of the library would be or pass me the library. thank you.
![Captura de pantalla 2019-03-30 a las 11 58 44](https://user-images.githubusercontent.com/23484201/55275244-8db4c900-52e3-11e9-9abb-5910b2085945.png)

**Comment by kernelcrash** [comment]
If you do a find down your library path you should see that file

`$ cd ../STM32F4-Discovery_FW_V1.1.0/
$ find . -name stm32f4xx.h
./Libraries/CMSIS/ST/STM32F4xx/Include/stm32f4xx.h`

I also checked the std periph zip:
`$ unzip -l en.stsw-stm32068.zip|grep stm32f4xx.h
   530693  10-28-2011 10:31   STM32F4-Discovery_FW_V1.1.0/Libraries/CMSIS/ST/STM32F4xx/Include/stm32f4xx.h
...`

**Comment by retrocant** [comment]
Greetings, the path ST / STM32F4xx / Include / stm32f4xx.h I do not have it in this folder (I attached capture), if you could pass me this library file I would appreciate it, because I do not have it.

receive a greeting.
![Captura de pantalla 2019-03-30 a las 20 39 06](https://user-images.githubusercontent.com/23484201/55280879-e3ad5f00-532b-11e9-840c-3753e8a28ff2.png)

**Comment by kernelcrash** [comment]
You're missing the entire ST directory. I'd go back to st.com, and redownload the en.stsw-stm32068.zip  from http://www.st.com/web/en/catalog/tools/PF257904# . If you don't want to do that, a quick search of GitHub for 'STM32F4-Discovery_FW_V1.1.0' will probably find other peoples projects where they've included the standard peripheral library (when they probably aren't meant to).

**Comment by retrocant** [comment]
Greetings, in the end I fixed it, I downloaded the folder in github with all the libraries and it has compiled perfectly to me in both Linux and Mac OS, mychas thanks for the help.

**Comment by kernelcrash** [comment]
Cool
